import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// Metadata
export const metadata = {
  title: 'Create Next App',
  applicationName: 'Create Next App',
  description: 'Generated by create next app',
  keywords: ['Next.js', 'React', 'TypeScript'],
  authors: [{ name: 'Emanuele Favero', url: 'https://emanuelefavero.com' }],
  creator: 'Emanuele',
  publisher: 'Emanuele',
  robots: {
    index: true, // make the page indexable
    follow: true, // make the links on the page followable
  },

  // TIP: Also add metadata for Open Graph, Icons, and others...
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <Link href='/'>Home</Link>
        </header>
        {children}
      </body>
    </html>
  )
}

// TIP: Layout components can fetch data
// TIP: You can't pass data between layout and its children, but if you fetch the same data in the layout and its children (on the same route), React will automatically memoize the requests without affecting performance
