import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <Link href='/'>Home</Link>
        </header>
        {children}
      </body>
    </html>
  )
}

// TIP: Layout components can fetch data
// TIP: You can't pass data between layout and its children, but if you fetch the same data in the layout and its children (on the same route), React will automatically memoize the requests without affecting performance
